import {
  Activity,
  Anchor,
  Aperture,
  Archive,
  Atom,
  Award,
  Banana,
  Battery,
  Beaker,
  Bell,
  Bike,
  Bird,
  Bitcoin,
  Blocks,
  Bomb,
  Book,
  BookOpen,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Bus,
  Cake,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  Cloud,
  Code,
  Coffee,
  Cog,
  Coins,
  Compass,
  Cpu,
  CreditCard,
  Crown,
  Database,
  Diamond,
  Dna,
  Dog,
  Droplet,
  Egg,
  Feather,
  Film,
  Flag,
  Flame,
  FlaskConical,
  Folder,
  FolderGit2,
  Gamepad2,
  Gauge,
  Gem,
  Ghost,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Hash,
  Headphones,
  Heart,
  Hexagon,
  House,
  Image,
  Inbox,
  Key,
  Keyboard,
  Laptop,
  Layers,
  Leaf,
  Lightbulb,
  Link,
  Lock,
  type LucideIcon,
  Mail,
  Map,
  MapPin,
  Medal,
  Megaphone,
  Microscope,
  Monitor,
  Moon,
  Mountain,
  Music,
  Network,
  Newspaper,
  Orbit,
  Package,
  Palette,
  Paperclip,
  PenTool,
  Phone,
  PieChart,
  PiggyBank,
  Pin,
  Pizza,
  Plane,
  Plug,
  Power,
  Printer,
  Puzzle,
  Rabbit,
  Radio,
  Rocket,
  Save,
  Scale,
  Scissors,
  Send,
  Server,
  Settings,
  Shield,
  Ship,
  ShoppingCart,
  Smartphone,
  Smile,
  Snowflake,
  Sparkles,
  Sprout,
  Square,
  Star,
  Sun,
  Sword,
  Tag,
  Target,
  Tent,
  Terminal,
  ThumbsUp,
  Timer,
  Train,
  TreePine,
  Trophy,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Video,
  Wallet,
  Watch,
  Waves,
  Wifi,
  Wind,
  Wrench,
  Zap,
} from "lucide-react";

export interface AvatarIcon {
  /** Stable id (kebab-case, English). Used as the React key, the picker's
   *  `data-testid`, and the English search match target. */
  id: string;
  /** German search synonyms (space-separated, lowercased) so the icon search
   *  works in DE as well as EN. Matching is locale-agnostic — both the English
   *  id and these terms are searched regardless of the active locale. */
  de: string;
  Icon: LucideIcon;
}

/** Curated icon set offered by the avatar designer. Broad enough that the
 *  search box earns its place; biased toward concrete, recognisable glyphs that
 *  read clearly at small avatar sizes. */
export const AVATAR_ICONS: readonly AvatarIcon[] = [
  { id: "folder", de: "ordner verzeichnis", Icon: Folder },
  { id: "folder-git", de: "ordner git verzeichnis", Icon: FolderGit2 },
  { id: "code", de: "code quelltext programmieren", Icon: Code },
  { id: "terminal", de: "terminal konsole shell", Icon: Terminal },
  { id: "git-branch", de: "branch zweig git", Icon: GitBranch },
  { id: "box", de: "box kiste schachtel paket", Icon: Box },
  { id: "boxes", de: "boxen kisten", Icon: Boxes },
  { id: "blocks", de: "blöcke bloecke bausteine", Icon: Blocks },
  { id: "package", de: "paket box", Icon: Package },
  { id: "puzzle", de: "puzzle rätsel raetsel teil", Icon: Puzzle },
  { id: "rocket", de: "rakete start launch", Icon: Rocket },
  { id: "star", de: "stern favorit", Icon: Star },
  { id: "heart", de: "herz liebe", Icon: Heart },
  { id: "zap", de: "blitz energie strom", Icon: Zap },
  { id: "flame", de: "flamme feuer", Icon: Flame },
  { id: "sparkles", de: "funkeln glitzer sterne magie", Icon: Sparkles },
  { id: "bolt", de: "aktivität aktivitaet puls welle", Icon: Activity },
  { id: "database", de: "datenbank daten", Icon: Database },
  { id: "server", de: "server", Icon: Server },
  { id: "cloud", de: "wolke cloud", Icon: Cloud },
  { id: "globe", de: "globus welt erde weltkugel", Icon: Globe },
  { id: "network", de: "netzwerk verbindung", Icon: Network },
  { id: "cpu", de: "prozessor chip cpu", Icon: Cpu },
  { id: "bug", de: "käfer kaefer fehler bug", Icon: Bug },
  { id: "wrench", de: "schraubenschlüssel schraubenschluessel werkzeug", Icon: Wrench },
  { id: "hammer", de: "hammer werkzeug", Icon: Hammer },
  { id: "cog", de: "zahnrad einstellungen getriebe", Icon: Cog },
  { id: "settings", de: "einstellungen optionen zahnrad", Icon: Settings },
  { id: "shield", de: "schild schutz sicherheit", Icon: Shield },
  { id: "lock", de: "schloss sperre sicherheit", Icon: Lock },
  { id: "key", de: "schlüssel schluessel", Icon: Key },
  { id: "atom", de: "atom physik", Icon: Atom },
  { id: "beaker", de: "becher labor", Icon: Beaker },
  { id: "flask", de: "kolben labor chemie", Icon: FlaskConical },
  { id: "microscope", de: "mikroskop labor", Icon: Microscope },
  { id: "dna", de: "dna gene biologie", Icon: Dna },
  { id: "brain", de: "gehirn hirn kopf", Icon: Brain },
  { id: "bot", de: "roboter bot ki", Icon: Bot },
  { id: "gauge", de: "tacho anzeige messung", Icon: Gauge },
  { id: "orbit", de: "umlaufbahn orbit planet", Icon: Orbit },
  { id: "compass", de: "kompass navigation", Icon: Compass },
  { id: "anchor", de: "anker schiff", Icon: Anchor },
  { id: "aperture", de: "blende kamera", Icon: Aperture },
  { id: "camera", de: "kamera foto", Icon: Camera },
  { id: "image", de: "bild foto grafik", Icon: Image },
  { id: "film", de: "film kino video", Icon: Film },
  { id: "video", de: "video kamera", Icon: Video },
  { id: "music", de: "musik note", Icon: Music },
  { id: "headphones", de: "kopfhörer kopfhoerer", Icon: Headphones },
  { id: "radio", de: "radio", Icon: Radio },
  { id: "palette", de: "palette farben malen", Icon: Palette },
  { id: "brush", de: "pinsel malen", Icon: Brush },
  { id: "pen-tool", de: "stift zeichnen feder", Icon: PenTool },
  { id: "feather", de: "feder schreiben", Icon: Feather },
  { id: "book", de: "buch lesen", Icon: Book },
  { id: "book-open", de: "buch offen lesen", Icon: BookOpen },
  { id: "bookmark", de: "lesezeichen merken", Icon: Bookmark },
  { id: "newspaper", de: "zeitung nachrichten", Icon: Newspaper },
  { id: "graduation-cap", de: "abschluss hut studium uni bildung", Icon: GraduationCap },
  { id: "lightbulb", de: "glühbirne gluehbirne idee licht", Icon: Lightbulb },
  { id: "flag", de: "flagge fahne", Icon: Flag },
  { id: "tag", de: "etikett tag schild label", Icon: Tag },
  { id: "pin", de: "pin nadel stecknadel", Icon: Pin },
  { id: "map", de: "karte landkarte", Icon: Map },
  { id: "map-pin", de: "standort markierung karte ort", Icon: MapPin },
  { id: "target", de: "ziel zielscheibe", Icon: Target },
  { id: "crown", de: "krone könig koenig", Icon: Crown },
  { id: "trophy", de: "pokal trophäe trophaee sieg", Icon: Trophy },
  { id: "medal", de: "medaille auszeichnung", Icon: Medal },
  { id: "award", de: "auszeichnung preis", Icon: Award },
  { id: "gem", de: "edelstein juwel", Icon: Gem },
  { id: "diamond", de: "diamant raute", Icon: Diamond },
  { id: "gift", de: "geschenk präsent praesent", Icon: Gift },
  { id: "cake", de: "kuchen torte geburtstag", Icon: Cake },
  { id: "coffee", de: "kaffee tasse", Icon: Coffee },
  { id: "pizza", de: "pizza essen", Icon: Pizza },
  { id: "banana", de: "banane obst", Icon: Banana },
  { id: "egg", de: "ei", Icon: Egg },
  { id: "leaf", de: "blatt natur pflanze", Icon: Leaf },
  { id: "sprout", de: "keimling pflanze spross", Icon: Sprout },
  { id: "tree", de: "baum tanne natur", Icon: TreePine },
  { id: "mountain", de: "berg gebirge", Icon: Mountain },
  { id: "sun", de: "sonne wetter", Icon: Sun },
  { id: "moon", de: "mond nacht", Icon: Moon },
  { id: "snowflake", de: "schneeflocke schnee winter", Icon: Snowflake },
  { id: "droplet", de: "tropfen wasser", Icon: Droplet },
  { id: "waves", de: "wellen wasser meer", Icon: Waves },
  { id: "wind", de: "wind wetter", Icon: Wind },
  { id: "umbrella", de: "regenschirm schirm", Icon: Umbrella },
  { id: "bird", de: "vogel tier", Icon: Bird },
  { id: "cat", de: "katze tier", Icon: Cat },
  { id: "dog", de: "hund tier", Icon: Dog },
  { id: "rabbit", de: "hase kaninchen tier", Icon: Rabbit },
  { id: "ghost", de: "geist gespenst", Icon: Ghost },
  { id: "bomb", de: "bombe", Icon: Bomb },
  { id: "sword", de: "schwert waffe", Icon: Sword },
  { id: "gamepad", de: "controller gamepad spiele gaming", Icon: Gamepad2 },
  { id: "bell", de: "glocke benachrichtigung", Icon: Bell },
  { id: "mail", de: "email brief post nachricht mail", Icon: Mail },
  { id: "inbox", de: "posteingang eingang", Icon: Inbox },
  { id: "send", de: "senden schicken", Icon: Send },
  { id: "phone", de: "telefon anruf", Icon: Phone },
  { id: "megaphone", de: "megafon lautsprecher ankündigung ankuendigung", Icon: Megaphone },
  { id: "smartphone", de: "smartphone handy telefon", Icon: Smartphone },
  { id: "laptop", de: "laptop notebook computer", Icon: Laptop },
  { id: "monitor", de: "monitor bildschirm computer", Icon: Monitor },
  { id: "tv", de: "fernseher tv", Icon: Tv },
  { id: "keyboard", de: "tastatur", Icon: Keyboard },
  { id: "printer", de: "drucker", Icon: Printer },
  { id: "battery", de: "batterie akku", Icon: Battery },
  { id: "plug", de: "stecker strom", Icon: Plug },
  { id: "power", de: "power ein aus strom", Icon: Power },
  { id: "wifi", de: "wlan wifi internet funk", Icon: Wifi },
  { id: "bitcoin", de: "bitcoin krypto währung waehrung", Icon: Bitcoin },
  { id: "coins", de: "münzen muenzen geld", Icon: Coins },
  { id: "credit-card", de: "kreditkarte karte zahlung", Icon: CreditCard },
  { id: "wallet", de: "geldbörse geldboerse brieftasche", Icon: Wallet },
  { id: "piggy-bank", de: "sparschwein sparen", Icon: PiggyBank },
  { id: "shopping-cart", de: "einkaufswagen warenkorb", Icon: ShoppingCart },
  { id: "scale", de: "waage gleichgewicht recht", Icon: Scale },
  { id: "calculator", de: "taschenrechner rechner", Icon: Calculator },
  { id: "pie-chart", de: "tortendiagramm diagramm statistik", Icon: PieChart },
  { id: "hash", de: "raute hash nummer", Icon: Hash },
  { id: "layers", de: "ebenen schichten", Icon: Layers },
  { id: "hexagon", de: "sechseck hexagon", Icon: Hexagon },
  { id: "square", de: "quadrat viereck", Icon: Square },
  { id: "archive", de: "archiv ablage", Icon: Archive },
  { id: "briefcase", de: "aktentasche koffer arbeit", Icon: Briefcase },
  { id: "calendar", de: "kalender termin datum", Icon: Calendar },
  { id: "timer", de: "timer stoppuhr zeit", Icon: Timer },
  { id: "watch", de: "uhr armbanduhr zeit", Icon: Watch },
  { id: "house", de: "haus zuhause heim", Icon: House },
  { id: "user", de: "benutzer person nutzer profil", Icon: User },
  { id: "users", de: "benutzer personen gruppe team", Icon: Users },
  { id: "smile", de: "lächeln laecheln smiley gesicht", Icon: Smile },
  { id: "thumbs-up", de: "daumen hoch gefällt gefaellt like", Icon: ThumbsUp },
  { id: "link", de: "link verknüpfung verknuepfung kette", Icon: Link },
  { id: "paperclip", de: "büroklammer bueroklammer anhang", Icon: Paperclip },
  { id: "scissors", de: "schere schneiden", Icon: Scissors },
  { id: "save", de: "speichern diskette", Icon: Save },
  { id: "tent", de: "zelt camping", Icon: Tent },
  { id: "plane", de: "flugzeug reise", Icon: Plane },
  { id: "car", de: "auto wagen fahrzeug", Icon: Car },
  { id: "bus", de: "bus", Icon: Bus },
  { id: "bike", de: "fahrrad rad velo", Icon: Bike },
  { id: "train", de: "zug bahn", Icon: Train },
  { id: "ship", de: "schiff boot", Icon: Ship },
  { id: "truck", de: "lkw lastwagen transport", Icon: Truck },
];
