import type { Organization, ProviderId, RemoteRepository } from "@recrest/shared";

import { daysAgo as daysAgoIso } from "@/lib/dev/seed/time";

/** Demo orgs the dev-stub returns from `list_remote_organizations`. */
export const SEED_ORGS: Partial<Record<ProviderId, Organization[]>> = {
  github: [
    {
      providerId: "github",
      id: "github-org-acme",
      slug: "acme-labs",
      displayName: "ACME Labs",
      avatarUrl: null,
    },
    {
      providerId: "github",
      id: "github-org-experiments",
      slug: "experiments",
      displayName: "Experiments",
      avatarUrl: null,
    },
  ],
  // GitLab groups intentionally include nested paths so the sidebar can render
  // them as a hierarchy (subgroups indented under their parent). Includes deep
  // nesting (4 levels) and long names to stress-test ellipsis/wrap behaviour.
  gitlab: [
    {
      providerId: "gitlab",
      id: "gitlab-group-benova",
      slug: "benova",
      displayName: "Benova",
      avatarUrl: null,
    },
    {
      providerId: "gitlab",
      id: "gitlab-group-benova-infra",
      slug: "benova/infrastructure",
      displayName: "Benova / Infrastructure",
      avatarUrl: null,
    },
    {
      providerId: "gitlab",
      id: "gitlab-group-benova-frontend",
      slug: "benova/frontend",
      displayName: "Benova / Frontend",
      avatarUrl: null,
    },
    {
      providerId: "gitlab",
      id: "gitlab-group-benova-infra-secrets",
      slug: "benova/infrastructure/secrets",
      displayName: "Benova / Infrastructure / Secrets",
      avatarUrl: null,
    },
    {
      providerId: "gitlab",
      id: "gitlab-group-benova-infra-secrets-vault",
      slug: "benova/infrastructure/secrets/vault-config-modules",
      displayName: "Benova / Infrastructure / Secrets / Vault Config Modules",
      avatarUrl: null,
    },
    {
      providerId: "gitlab",
      id: "gitlab-group-benova-infra-platform",
      slug: "benova/infrastructure/platform-engineering-tooling",
      displayName: "Benova / Infrastructure / Platform Engineering Tooling",
      avatarUrl: null,
    },
    {
      providerId: "gitlab",
      id: "gitlab-group-tooling",
      slug: "tooling",
      displayName: "Tooling",
      avatarUrl: null,
    },
    {
      providerId: "gitlab",
      id: "gitlab-group-long",
      slug: "extremely-long-organization-name-for-stress-testing-ellipsis-behavior",
      displayName: "Extremely Long Organization Name For Stress Testing Ellipsis Behavior",
      avatarUrl: null,
    },
  ],
};

/** Demo remote-repository listings the dev-stub returns from
 *  `list_remote_repositories`. Keyed by `${providerId}::${orgSlug ?? "__self__"}`. */
export const SEED_REMOTE_LISTINGS: Record<string, RemoteRepository[]> = {
  "github::__self__": [
    {
      providerId: "github",
      id: "gh-remote-recrest",
      fullName: "demo-user/recrest",
      name: "recrest",
      description: "Native developer dashboard for git repos.",
      defaultBranch: "main",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/demo-user/recrest.git",
      cloneUrlSsh: "git@github.com:demo-user/recrest.git",
      htmlUrl: "https://github.com/demo-user/recrest",
      updatedAt: daysAgoIso(1),
      pushedAt: daysAgoIso(1),
      sizeKb: 4096,
      language: "TypeScript",
      ownerLogin: "demo-user",
      ownerAvatarUrl: null,
    },
    {
      providerId: "github",
      id: "gh-remote-dotfiles",
      fullName: "demo-user/dotfiles",
      name: "dotfiles",
      description: "Personal dotfiles, zsh and nvim configs.",
      defaultBranch: "main",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/demo-user/dotfiles.git",
      cloneUrlSsh: "git@github.com:demo-user/dotfiles.git",
      htmlUrl: "https://github.com/demo-user/dotfiles",
      updatedAt: daysAgoIso(7),
      pushedAt: daysAgoIso(7),
      sizeKb: 512,
      language: "Shell",
      ownerLogin: "demo-user",
      ownerAvatarUrl: null,
    },
    {
      providerId: "github",
      id: "gh-remote-blog",
      fullName: "demo-user/blog",
      name: "blog",
      description: "Personal blog — markdown + Astro.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/demo-user/blog.git",
      cloneUrlSsh: "git@github.com:demo-user/blog.git",
      htmlUrl: "https://github.com/demo-user/blog",
      updatedAt: daysAgoIso(14),
      pushedAt: daysAgoIso(14),
      sizeKb: 8192,
      language: "Astro",
      ownerLogin: "demo-user",
      ownerAvatarUrl: null,
    },
    {
      providerId: "github",
      id: "gh-remote-experiments",
      fullName: "demo-user/cli-experiments",
      name: "cli-experiments",
      description: null,
      defaultBranch: "main",
      isPrivate: false,
      isFork: true,
      isArchived: true,
      cloneUrlHttps: "https://github.com/demo-user/cli-experiments.git",
      cloneUrlSsh: "git@github.com:demo-user/cli-experiments.git",
      htmlUrl: "https://github.com/demo-user/cli-experiments",
      updatedAt: daysAgoIso(180),
      pushedAt: daysAgoIso(180),
      sizeKb: 256,
      language: "Rust",
      ownerLogin: "demo-user",
      ownerAvatarUrl: null,
    },
  ],
  "github::acme-labs": [
    {
      providerId: "github",
      id: "gh-remote-ledger-api",
      fullName: "acme-labs/ledger-api",
      name: "ledger-api",
      description: "Double-entry ledger REST API.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/acme-labs/ledger-api.git",
      cloneUrlSsh: "git@github.com:acme-labs/ledger-api.git",
      htmlUrl: "https://github.com/acme-labs/ledger-api",
      updatedAt: daysAgoIso(2),
      pushedAt: daysAgoIso(2),
      sizeKb: 12288,
      language: "Go",
      ownerLogin: "acme-labs",
      ownerAvatarUrl: null,
    },
    {
      providerId: "github",
      id: "gh-remote-pulse-ios",
      fullName: "acme-labs/pulse-ios",
      name: "pulse-ios",
      description: "iOS companion for the Pulse platform.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/acme-labs/pulse-ios.git",
      cloneUrlSsh: "git@github.com:acme-labs/pulse-ios.git",
      htmlUrl: "https://github.com/acme-labs/pulse-ios",
      updatedAt: daysAgoIso(5),
      pushedAt: daysAgoIso(5),
      sizeKb: 22528,
      language: "Swift",
      ownerLogin: "acme-labs",
      ownerAvatarUrl: null,
    },
  ],
  "github::experiments": [
    {
      providerId: "github",
      id: "gh-remote-glyph-sandbox",
      fullName: "experiments/glyph-sandbox",
      name: "glyph-sandbox",
      description: "Variable-font playground.",
      defaultBranch: "main",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/experiments/glyph-sandbox.git",
      cloneUrlSsh: "git@github.com:experiments/glyph-sandbox.git",
      htmlUrl: "https://github.com/experiments/glyph-sandbox",
      updatedAt: daysAgoIso(21),
      pushedAt: daysAgoIso(21),
      sizeKb: 1024,
      language: "JavaScript",
      ownerLogin: "experiments",
      ownerAvatarUrl: null,
    },
  ],
  "gitlab::benova": [
    {
      providerId: "gitlab",
      id: "gl-benova-platform",
      fullName: "benova/platform",
      name: "platform",
      description: "Core platform monorepo.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://gitlab.com/benova/platform.git",
      cloneUrlSsh: "git@gitlab.com:benova/platform.git",
      htmlUrl: "https://gitlab.com/benova/platform",
      updatedAt: daysAgoIso(2),
      pushedAt: daysAgoIso(2),
      sizeKb: 32768,
      language: "TypeScript",
      ownerLogin: "benova",
      ownerAvatarUrl: null,
    },
  ],
  "gitlab::benova/infrastructure": [
    {
      providerId: "gitlab",
      id: "gl-benova-infra-terraform",
      fullName: "benova/infrastructure/terraform",
      name: "terraform",
      description: "Terraform modules for prod.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://gitlab.com/benova/infrastructure/terraform.git",
      cloneUrlSsh: "git@gitlab.com:benova/infrastructure/terraform.git",
      htmlUrl: "https://gitlab.com/benova/infrastructure/terraform",
      updatedAt: daysAgoIso(4),
      pushedAt: daysAgoIso(4),
      sizeKb: 6144,
      language: "HCL",
      ownerLogin: "benova/infrastructure",
      ownerAvatarUrl: null,
    },
  ],
  "gitlab::benova/frontend": [
    {
      providerId: "gitlab",
      id: "gl-benova-frontend-portal",
      fullName: "benova/frontend/portal",
      name: "portal",
      description: "Customer-facing portal (Next.js).",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://gitlab.com/benova/frontend/portal.git",
      cloneUrlSsh: "git@gitlab.com:benova/frontend/portal.git",
      htmlUrl: "https://gitlab.com/benova/frontend/portal",
      updatedAt: daysAgoIso(3),
      pushedAt: daysAgoIso(3),
      sizeKb: 10240,
      language: "TypeScript",
      ownerLogin: "benova/frontend",
      ownerAvatarUrl: null,
    },
  ],
  "gitlab::benova/infrastructure/secrets": [
    {
      providerId: "gitlab",
      id: "gl-benova-infra-secrets-vault",
      fullName: "benova/infrastructure/secrets/vault-config",
      name: "vault-config",
      description: "HashiCorp Vault config.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://gitlab.com/benova/infrastructure/secrets/vault-config.git",
      cloneUrlSsh: "git@gitlab.com:benova/infrastructure/secrets/vault-config.git",
      htmlUrl: "https://gitlab.com/benova/infrastructure/secrets/vault-config",
      updatedAt: daysAgoIso(6),
      pushedAt: daysAgoIso(6),
      sizeKb: 512,
      language: "HCL",
      ownerLogin: "benova/infrastructure/secrets",
      ownerAvatarUrl: null,
    },
    {
      providerId: "gitlab",
      id: "gl-benova-infra-secrets-very-long",
      fullName:
        "benova/infrastructure/secrets/extremely-long-repository-name-for-stress-testing-row-overflow-and-ellipsis",
      name: "extremely-long-repository-name-for-stress-testing-row-overflow-and-ellipsis",
      description:
        "A repo with an intentionally very long name to verify overflow handling in the rows.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps:
        "https://gitlab.com/benova/infrastructure/secrets/extremely-long-repository-name-for-stress-testing-row-overflow-and-ellipsis.git",
      cloneUrlSsh: null,
      htmlUrl:
        "https://gitlab.com/benova/infrastructure/secrets/extremely-long-repository-name-for-stress-testing-row-overflow-and-ellipsis",
      updatedAt: daysAgoIso(8),
      pushedAt: daysAgoIso(8),
      sizeKb: 1024,
      language: "HCL",
      ownerLogin: "benova/infrastructure/secrets",
      ownerAvatarUrl: null,
    },
  ],
  "gitlab::benova/infrastructure/secrets/vault-config-modules": [
    {
      providerId: "gitlab",
      id: "gl-vault-modules-aws",
      fullName: "benova/infrastructure/secrets/vault-config-modules/aws-kms-backed-transit",
      name: "aws-kms-backed-transit",
      description: "AWS-KMS-backed transit engine module.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps:
        "https://gitlab.com/benova/infrastructure/secrets/vault-config-modules/aws-kms-backed-transit.git",
      cloneUrlSsh: null,
      htmlUrl:
        "https://gitlab.com/benova/infrastructure/secrets/vault-config-modules/aws-kms-backed-transit",
      updatedAt: daysAgoIso(15),
      pushedAt: daysAgoIso(15),
      sizeKb: 256,
      language: "HCL",
      ownerLogin: "benova/infrastructure/secrets/vault-config-modules",
      ownerAvatarUrl: null,
    },
  ],
  "gitlab::tooling": [
    {
      providerId: "gitlab",
      id: "gl-tooling-cli",
      fullName: "tooling/cli",
      name: "cli",
      description: "Internal CLI tool.",
      defaultBranch: "main",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://gitlab.com/tooling/cli.git",
      cloneUrlSsh: "git@gitlab.com:tooling/cli.git",
      htmlUrl: "https://gitlab.com/tooling/cli",
      updatedAt: daysAgoIso(11),
      pushedAt: daysAgoIso(11),
      sizeKb: 2048,
      language: "Go",
      ownerLogin: "tooling",
      ownerAvatarUrl: null,
    },
  ],
};
