import type { Organization, ProviderId, RemoteRepository } from "@recrest/shared";

const today = new Date();
const daysAgoIso = (d: number): string => {
  const dt = new Date(today);
  dt.setDate(dt.getDate() - d);
  return dt.toISOString();
};

/** Demo orgs the dev-stub returns from `list_remote_organizations`. */
export const SEED_ORGS: Partial<Record<ProviderId, Organization[]>> = {
  github: [
    {
      providerId: "github",
      id: "github-org-acme",
      slug: "acme-labs",
      displayName: "ACME Labs",
      avatarUrl: null,
    },
    {
      providerId: "github",
      id: "github-org-experiments",
      slug: "experiments",
      displayName: "Experiments",
      avatarUrl: null,
    },
  ],
};

/** Demo remote-repository listings the dev-stub returns from
 *  `list_remote_repositories`. Keyed by `${providerId}::${orgSlug ?? "__self__"}`. */
export const SEED_REMOTE_LISTINGS: Record<string, RemoteRepository[]> = {
  "github::__self__": [
    {
      providerId: "github",
      id: "gh-remote-recrest",
      fullName: "valentin/recrest",
      name: "recrest",
      description: "Native developer dashboard for git repos.",
      defaultBranch: "main",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/valentin/recrest.git",
      cloneUrlSsh: "git@github.com:valentin/recrest.git",
      htmlUrl: "https://github.com/valentin/recrest",
      updatedAt: daysAgoIso(1),
      pushedAt: daysAgoIso(1),
      sizeKb: 4096,
      language: "TypeScript",
      ownerLogin: "valentin",
      ownerAvatarUrl: null,
    },
    {
      providerId: "github",
      id: "gh-remote-dotfiles",
      fullName: "valentin/dotfiles",
      name: "dotfiles",
      description: "Personal dotfiles, zsh and nvim configs.",
      defaultBranch: "main",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/valentin/dotfiles.git",
      cloneUrlSsh: "git@github.com:valentin/dotfiles.git",
      htmlUrl: "https://github.com/valentin/dotfiles",
      updatedAt: daysAgoIso(7),
      pushedAt: daysAgoIso(7),
      sizeKb: 512,
      language: "Shell",
      ownerLogin: "valentin",
      ownerAvatarUrl: null,
    },
    {
      providerId: "github",
      id: "gh-remote-blog",
      fullName: "valentin/blog",
      name: "blog",
      description: "Personal blog — markdown + Astro.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/valentin/blog.git",
      cloneUrlSsh: "git@github.com:valentin/blog.git",
      htmlUrl: "https://github.com/valentin/blog",
      updatedAt: daysAgoIso(14),
      pushedAt: daysAgoIso(14),
      sizeKb: 8192,
      language: "Astro",
      ownerLogin: "valentin",
      ownerAvatarUrl: null,
    },
    {
      providerId: "github",
      id: "gh-remote-experiments",
      fullName: "valentin/cli-experiments",
      name: "cli-experiments",
      description: null,
      defaultBranch: "main",
      isPrivate: false,
      isFork: true,
      isArchived: true,
      cloneUrlHttps: "https://github.com/valentin/cli-experiments.git",
      cloneUrlSsh: "git@github.com:valentin/cli-experiments.git",
      htmlUrl: "https://github.com/valentin/cli-experiments",
      updatedAt: daysAgoIso(180),
      pushedAt: daysAgoIso(180),
      sizeKb: 256,
      language: "Rust",
      ownerLogin: "valentin",
      ownerAvatarUrl: null,
    },
  ],
  "github::acme-labs": [
    {
      providerId: "github",
      id: "gh-remote-ledger-api",
      fullName: "acme-labs/ledger-api",
      name: "ledger-api",
      description: "Double-entry ledger REST API.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/acme-labs/ledger-api.git",
      cloneUrlSsh: "git@github.com:acme-labs/ledger-api.git",
      htmlUrl: "https://github.com/acme-labs/ledger-api",
      updatedAt: daysAgoIso(2),
      pushedAt: daysAgoIso(2),
      sizeKb: 12288,
      language: "Go",
      ownerLogin: "acme-labs",
      ownerAvatarUrl: null,
    },
    {
      providerId: "github",
      id: "gh-remote-pulse-ios",
      fullName: "acme-labs/pulse-ios",
      name: "pulse-ios",
      description: "iOS companion for the Pulse platform.",
      defaultBranch: "main",
      isPrivate: true,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/acme-labs/pulse-ios.git",
      cloneUrlSsh: "git@github.com:acme-labs/pulse-ios.git",
      htmlUrl: "https://github.com/acme-labs/pulse-ios",
      updatedAt: daysAgoIso(5),
      pushedAt: daysAgoIso(5),
      sizeKb: 22528,
      language: "Swift",
      ownerLogin: "acme-labs",
      ownerAvatarUrl: null,
    },
  ],
  "github::experiments": [
    {
      providerId: "github",
      id: "gh-remote-glyph-sandbox",
      fullName: "experiments/glyph-sandbox",
      name: "glyph-sandbox",
      description: "Variable-font playground.",
      defaultBranch: "main",
      isPrivate: false,
      isFork: false,
      isArchived: false,
      cloneUrlHttps: "https://github.com/experiments/glyph-sandbox.git",
      cloneUrlSsh: "git@github.com:experiments/glyph-sandbox.git",
      htmlUrl: "https://github.com/experiments/glyph-sandbox",
      updatedAt: daysAgoIso(21),
      pushedAt: daysAgoIso(21),
      sizeKb: 1024,
      language: "JavaScript",
      ownerLogin: "experiments",
      ownerAvatarUrl: null,
    },
  ],
};
