use async_trait::async_trait;

use super::api::{
    CheckRunSummaryDto, OrganizationDto, PrEventDto, PullRequestDetailDto, PullRequestDto,
    RemoteRepositoryDto,
};
use crate::commands::error::CommandError;

/// Contract every git platform provider must implement. Designed so that it
/// can be re-expressed as a WASM plugin interface later without API churn.
#[async_trait]
pub trait GitProvider: Send + Sync {
    fn id(&self) -> &'static str;
    fn display_name(&self) -> &'static str;

    async fn is_authenticated(&self) -> Result<bool, CommandError>;
    async fn username(&self) -> Result<Option<String>, CommandError>;
    async fn set_token(&self, token: &str, username: Option<&str>) -> Result<(), CommandError>;
    async fn clear_token(&self) -> Result<(), CommandError>;

    /// Override the API base URL for self-hosted instances (GitHub Enterprise,
    /// GitLab self-managed, Bitbucket Server). `None` clears the override and
    /// falls back to the provider's built-in cloud default.
    async fn set_base_url(&self, _base_url: Option<String>) -> Result<(), CommandError> {
        Ok(())
    }

    /// The currently-effective API base URL — either the user override (if
    /// set) or the built-in cloud default. Used by the UI to display the
    /// self-hosted chip + the "Change API base URL" form's initial value.
    async fn base_url(&self) -> Option<String> {
        None
    }

    async fn list_pull_requests(&self, remote_url: &str) -> Result<Vec<PullRequestDto>, CommandError>;

    /// PR/MR life-cycle events (opened / merged / closed) within the last
    /// `days` days. Default impl returns an empty list so providers that
    /// don't support it yet don't break the Activity page.
    async fn list_pr_events(
        &self,
        _remote_url: &str,
        _days: u32,
        _repo_id: &str,
        _repo_name: &str,
    ) -> Result<Vec<PrEventDto>, CommandError> {
        Ok(Vec::new())
    }

    /// CI check-runs for the supplied commit SHAs, aggregated per local day.
    /// `local_tz_offset_minutes` carries the user's current UTC offset so the
    /// backend groups runs into the same day boundaries the UI renders on.
    async fn list_check_runs(
        &self,
        _remote_url: &str,
        _shas: &[String],
        _repo_id: &str,
        _repo_name: &str,
        _local_tz_offset_minutes: i32,
    ) -> Result<Vec<CheckRunSummaryDto>, CommandError> {
        Ok(Vec::new())
    }

    /// PR detail (reviewers, files, timeline). Default impl errors out so
    /// partially-implemented providers keep compiling — callers get a clean
    /// "not implemented" back instead of a type-level hole.
    async fn get_pull_request_detail(
        &self,
        _remote_url: &str,
        _pr_number: u64,
    ) -> Result<PullRequestDetailDto, CommandError> {
        Err(CommandError::bad_request(format!(
            "{}: get_pull_request_detail is not implemented",
            self.id()
        )))
    }

    /// All repositories the authenticated user can access (owned + member of).
    async fn list_repositories(&self) -> Result<Vec<RemoteRepositoryDto>, CommandError> {
        Err(CommandError::bad_request(format!(
            "{}: list_repositories is not implemented",
            self.id()
        )))
    }

    /// Orgs / groups / workspaces the user belongs to. Empty list is valid
    /// (user has no orgs); the UI shows only "My repos" in that case.
    async fn list_organizations(&self) -> Result<Vec<OrganizationDto>, CommandError> {
        Ok(Vec::new())
    }

    /// Repos scoped to a single org/group/workspace. Used when the user drills
    /// down in the import dialog's provider sidebar.
    async fn list_repositories_for_org(
        &self,
        _org_slug: &str,
    ) -> Result<Vec<RemoteRepositoryDto>, CommandError> {
        Err(CommandError::bad_request(format!(
            "{}: list_repositories_for_org is not implemented",
            self.id()
        )))
    }

    /// Whether this provider has a registered OAuth app configured at compile
    /// time. Returning `false` (the default) tells the UI to hide the
    /// "Connect via browser" button and only surface the PAT flow.
    fn supports_oauth(&self) -> bool {
        false
    }

    /// Returns the authorize-url the user should be sent to in their browser
    /// to begin an OAuth flow. `state` is a CSRF nonce generated by the
    /// caller — providers MUST include it verbatim in the returned URL so
    /// the callback handler can match the response.
    async fn authorize_url(
        &self,
        _redirect_uri: &str,
        _state: &str,
    ) -> Result<String, CommandError> {
        Err(CommandError::bad_request(format!(
            "{}: OAuth is not configured",
            self.id()
        )))
    }

    /// Exchanges the `code` returned from the OAuth callback for an access
    /// token and persists it in the keychain. Providers should verify the
    /// state on the caller side before invoking this.
    async fn exchange_code(
        &self,
        _code: &str,
        _redirect_uri: &str,
    ) -> Result<(), CommandError> {
        Err(CommandError::bad_request(format!(
            "{}: OAuth is not configured",
            self.id()
        )))
    }
}
