import type { PullRequest, RepositoryId } from "@recrest/shared";

/**
 * 12 pull/merge requests distributed across the seeded repos. Roughly half
 * open/draft/merged so filters have something to chew on.
 */
export const SEED_PRS: Record<RepositoryId, PullRequest[]> = {
  "repo-recrest": [
    {
      id: "pr-recrest-41",
      number: 41,
      title: "feat(landing): realistic hero demo with DE/EN copy",
      url: "https://github.com/SoftVentures/Recrest/pull/41",
      author: "valentin",
      state: "open",
      draft: false,
      sourceBranch: "feat/landing-hero",
      targetBranch: "main",
      createdAt: "2026-04-16T09:00:00Z",
      updatedAt: "2026-04-18T16:10:00Z",
      additions: 482,
      deletions: 117,
      ciStatus: "success",
    },
    {
      id: "pr-recrest-38",
      number: 38,
      title: "ci(tests): bootstrap Playwright suite",
      url: "https://github.com/SoftVentures/Recrest/pull/38",
      author: "valentin",
      state: "open",
      draft: true,
      sourceBranch: "ci/playwright",
      targetBranch: "main",
      createdAt: "2026-04-17T14:05:00Z",
      updatedAt: "2026-04-19T10:22:00Z",
      additions: 912,
      deletions: 14,
      ciStatus: "running",
    },
  ],
  "repo-local-dev-stacks": [
    {
      id: "pr-lds-22",
      number: 22,
      title: "compose-v2: split profiles",
      url: "https://github.com/SoftVentures/local-dev-stacks/pull/22",
      author: "valentin",
      state: "open",
      draft: false,
      sourceBranch: "feat/compose-v2",
      targetBranch: "main",
      createdAt: "2026-04-15T18:00:00Z",
      updatedAt: "2026-04-17T21:04:00Z",
      additions: 112,
      deletions: 48,
      ciStatus: "failure",
    },
  ],
  "repo-ledger-api": [],
  "repo-pulse-ios": [
    {
      id: "pr-pulse-117",
      number: 117,
      title: "feat(home): redesign hero timeline",
      url: "https://gitlab.com/acme-labs/pulse-ios/-/merge_requests/117",
      author: "tomi",
      state: "open",
      draft: false,
      sourceBranch: "feat/home-v2",
      targetBranch: "main",
      createdAt: "2026-04-15T12:00:00Z",
      updatedAt: "2026-04-18T11:19:00Z",
      additions: 398,
      deletions: 142,
      ciStatus: "pending",
    },
    {
      id: "pr-pulse-115",
      number: 115,
      title: "fix(alerts): respect notification throttling",
      url: "https://gitlab.com/acme-labs/pulse-ios/-/merge_requests/115",
      author: "luis",
      state: "open",
      draft: false,
      sourceBranch: "fix/alert-throttle",
      targetBranch: "main",
      createdAt: "2026-04-14T10:20:00Z",
      updatedAt: "2026-04-16T07:44:00Z",
      additions: 74,
      deletions: 21,
      ciStatus: "success",
    },
  ],
  "repo-starlight-ui": [
    {
      id: "pr-star-204",
      number: 204,
      title: "fix(button): retain focus ring after click",
      url: "https://github.com/acme-labs/starlight-ui/pull/204",
      author: "lea",
      state: "open",
      draft: false,
      sourceBranch: "fix/button-focus",
      targetBranch: "main",
      createdAt: "2026-04-16T09:15:00Z",
      updatedAt: "2026-04-16T13:05:00Z",
      additions: 12,
      deletions: 4,
      ciStatus: "success",
    },
    {
      id: "pr-star-201",
      number: 201,
      title: "feat(table): sticky header with shadow on scroll",
      url: "https://github.com/acme-labs/starlight-ui/pull/201",
      author: "lea",
      state: "open",
      draft: true,
      sourceBranch: "feat/sticky-table",
      targetBranch: "main",
      createdAt: "2026-04-12T09:00:00Z",
      updatedAt: "2026-04-13T17:00:00Z",
      additions: 188,
      deletions: 34,
      ciStatus: "none",
    },
    {
      id: "pr-star-198",
      number: 198,
      title: "ci(deps): bump storybook to 8.3",
      url: "https://github.com/acme-labs/starlight-ui/pull/198",
      author: "renovate-bot",
      state: "merged",
      draft: false,
      sourceBranch: "renovate/storybook-8.3",
      targetBranch: "main",
      createdAt: "2026-04-09T03:15:00Z",
      updatedAt: "2026-04-11T09:00:00Z",
      additions: 214,
      deletions: 89,
      ciStatus: "success",
    },
  ],
  "repo-octo-notes": [],
  "repo-glyph-sandbox": [],
  "repo-signal-lab": [
    {
      id: "pr-signal-9",
      number: 9,
      title: "ci(deps): quarterly bump",
      url: "https://bitbucket.org/valentin/signal-lab/pull-requests/9",
      author: "valentin",
      state: "open",
      draft: false,
      sourceBranch: "ci/deps",
      targetBranch: "main",
      createdAt: "2026-04-10T12:00:00Z",
      updatedAt: "2026-04-10T12:00:00Z",
      additions: 28,
      deletions: 22,
      ciStatus: "none",
    },
  ],
};

/** Count of PRs per state across the seed — handy for sidebar-count assertions. */
export const SEED_PR_COUNTS = {
  open: 8,
  draft: 2,
  merged: 1,
  total: 9,
} as const;
